export const HOUSEDESIGN_LIST_REQUEST = 'HOUSEDESIGN_LIST_REQUEST';
export const HOUSEDESIGN_LIST_SUCCESS = 'HOUSEDESIGN_LIST_SUCCESS';
export const HOUSEDESIGN_LIST_FAIL = 'HOUSEDESIGN_LIST_FAIL';

export const HOUSEDESIGN_DETAILS_REQUEST = 'HOUSEDESIGN_DETAILS_REQUEST';
export const HOUSEDESIGN_DETAILS_SUCCESS = 'HOUSEDESIGN_DETAILS_SUCCESS';
export const HOUSEDESIGN_DETAILS_FAIL = 'HOUSEDESIGN_DETAILS_FAIL';
